# Generated by Django 5.2.8 on 2026-02-27 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender', 'receiver', 'status'], name='fr_sender_receiver_status_idx'),
        ),
    ]
