# Generated by Django 5.2.8 on 2026-02-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest_fr_sender_receiver_status_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
