# Generated by Django 5.2.8 on 2026-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
