# Generated by Django 5.2.8 on 2026-01-27 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travelkit_items/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Janaki', 'Janaki'), ('Lumbini', 'Lumbini'), ('Bhaktapur', 'Bhaktapur'), ('Dhaulagiri', 'Dhaulagiri'), ('Gaurishankar', 'Gaurishankar'), ('Annapurna', 'Annapurna'), ('EverestRegion', 'Everest Region'), ('LangtangNationalPark', 'Langtang National Park'), ('Ghorepani', 'Ghorepani'), ('Ghandruk', 'Ghandruk'), ('GosaikundaLake', 'Gosaikunda Lake'), ('Machhapuchhre', 'Machhapuchhre'), ('Khaptad', 'Khaptad'), ('KoshiTappu', 'Koshi Tappu'), ('Rara', 'Rara'), ('Shey', 'Shey'), ('SheyLake', 'Shey Lake'), ('Bardia', 'Bardia'), ('Dharan', 'Dharan'), ('Illam', 'Illam'), ('Lalitpur', 'Lalitpur'), ('Other', 'Other')], default='Other', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Gallery',
                'verbose_name_plural': 'Photo Galleries',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
