# Generated by Django 5.2.8 on 2026-02-12 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travelkit_items/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('location', models.CharField(choices=[('Illam', 'Illam'), ('Dharan', 'Dharan'), ('Koshi Tappu', 'Koshi Tappu'), ('Mt Everest Base Camp', 'Mt Everest Base Camp'), ('Makalu Trek (Everest Region)', 'Makalu Trek (Everest Region)'), ('Mt Everest (Summit attempt)', 'Mt Everest (Summit attempt)'), ('Janaki Temple', 'Janaki Temple'), ('Gaurishankar Region Trek', 'Gaurishankar Region Trek'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Langtang Valley (Trek)', 'Langtang Valley (Trek)'), ('Gosaikunda Lake', 'Gosaikunda Lake'), ('Machapuchare (Fishtail)', 'Machapuchare (Fishtail)'), ('Ghandruk Village', 'Ghandruk Village'), ('Pokhara', 'Pokhara'), ('Phewa Lake', 'Phewa Lake'), ('Ghorepani–Poon Hill', 'Ghorepani–Poon Hill'), ('Annapurna Circuit', 'Annapurna Circuit'), ('Annapurna Base Camp (ABC) Trek', 'Annapurna Base Camp (ABC) Trek'), ('Dhaulagiri Circuit Trek', 'Dhaulagiri Circuit Trek'), ('Lumbini', 'Lumbini'), ('Bardia National Park', 'Bardia National Park'), ('Langtang National Park', 'Langtang National Park'), ('Sagarmatha National Park', 'Sagarmatha National Park'), ('Rara Lake', 'Rara Lake'), ('Rara National Park', 'Rara National Park'), ('Shey Phoksundo Lake', 'Shey Phoksundo Lake'), ('Shey Phoksundo National Park', 'Shey Phoksundo National Park'), ('Api Mountain', 'Api Mountain'), ('Khaptad National Park', 'Khaptad National Park'), ('Mustang', 'Mustang'), ('Manang', 'Manang'), ('Other', 'Other')], default='Other', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, photo is visible to all users. If False, only you can see it.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Gallery',
                'verbose_name_plural': 'Photo Galleries',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Janaki', 'Janaki'), ('Lumbini', 'Lumbini'), ('Bhaktapur', 'Bhaktapur'), ('Dhaulagiri', 'Dhaulagiri'), ('Gaurishankar', 'Gaurishankar'), ('Annapurna', 'Annapurna'), ('EverestRegion', 'Everest Region'), ('LangtangNationalPark', 'Langtang National Park'), ('Ghorepani', 'Ghorepani'), ('Ghandruk', 'Ghandruk'), ('GosaikundaLake', 'Gosaikunda Lake'), ('Machhapuchhre', 'Machhapuchhre'), ('Khaptad', 'Khaptad'), ('KoshiTappu', 'Koshi Tappu'), ('Rara', 'Rara'), ('Shey', 'Shey'), ('SheyLake', 'Shey Lake'), ('Bardia', 'Bardia'), ('Dharan', 'Dharan'), ('Illam', 'Illam'), ('Lalitpur', 'Lalitpur'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Location',
                'verbose_name_plural': 'Favorite Locations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photo_gallery.photogallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Like',
                'verbose_name_plural': 'Photo Likes',
                'ordering': ['-created_at'],
                'unique_together': {('photo', 'user')},
            },
        ),
    ]
