# Generated by Django 5.2.8 on 2026-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, photo is visible to all users. If False, only you can see it.'),
        ),
    ]
