# Generated by Django 5.2.8 on 2026-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Janaki', 'Janaki'), ('Lumbini', 'Lumbini'), ('Bhaktapur', 'Bhaktapur'), ('Dhaulagiri', 'Dhaulagiri'), ('Gaurishankar', 'Gaurishankar'), ('Annapurna', 'Annapurna'), ('EverestRegion', 'Everest Region'), ('LangtangNationalPark', 'Langtang National Park'), ('Ghorepani', 'Ghorepani'), ('Ghandruk', 'Ghandruk'), ('GosaikundaLake', 'Gosaikunda Lake'), ('Machhapuchhre', 'Machhapuchhre'), ('Khaptad', 'Khaptad'), ('KoshiTappu', 'Koshi Tappu'), ('Rara', 'Rara'), ('Shey', 'Shey'), ('SheyLake', 'Shey Lake'), ('Bardia', 'Bardia'), ('Dharan', 'Dharan'), ('Illam', 'Illam'), ('Lalitpur', 'Lalitpur'), ('Api', 'Api'), ('Other', 'Other')], max_length=50),
        ),
    ]
