# Generated by Django 5.2.8 on 2026-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_alter_favoritelocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='location',
            field=models.CharField(choices=[('Illam', 'Illam'), ('Dharan', 'Dharan'), ('Koshi Tappu', 'Koshi Tappu'), ('Mt Everest Base Camp', 'Mt Everest Base Camp'), ('Makalu Trek (Everest Region)', 'Makalu Trek (Everest Region)'), ('Mt Everest (Summit attempt)', 'Mt Everest (Summit attempt)'), ('Janaki Temple', 'Janaki Temple'), ('Gaurishankar Region Trek', 'Gaurishankar Region Trek'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Langtang Valley (Trek)', 'Langtang Valley (Trek)'), ('Gosaikunda Lake', 'Gosaikunda Lake'), ('Machapuchare (Fishtail)', 'Machapuchare (Fishtail)'), ('Ghandruk Village', 'Ghandruk Village'), ('Pokhara', 'Pokhara'), ('Phewa Lake', 'Phewa Lake'), ('Ghorepani–Poon Hill', 'Ghorepani–Poon Hill'), ('Annapurna Circuit', 'Annapurna Circuit'), ('Annapurna Base Camp (ABC) Trek', 'Annapurna Base Camp (ABC) Trek'), ('Dhaulagiri Circuit Trek', 'Dhaulagiri Circuit Trek'), ('Lumbini', 'Lumbini'), ('Bardia National Park', 'Bardia National Park'), ('Langtang National Park', 'Langtang National Park'), ('Sagarmatha National Park', 'Sagarmatha National Park'), ('Rara Lake', 'Rara Lake'), ('Rara National Park', 'Rara National Park'), ('Shey Phoksundo Lake', 'Shey Phoksundo Lake'), ('Shey Phoksundo National Park', 'Shey Phoksundo National Park'), ('Api Mountain', 'Api Mountain'), ('Khaptad National Park', 'Khaptad National Park'), ('Mustang', 'Mustang'), ('Manang', 'Manang'), ('Other', 'Other')], max_length=50),
        ),
    ]
