# Generated by Django 5.2.8 on 2026-01-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_photolike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Janaki', 'Janaki'), ('Lumbini', 'Lumbini'), ('Bhaktapur', 'Bhaktapur'), ('Dhaulagiri', 'Dhaulagiri'), ('Gaurishankar', 'Gaurishankar'), ('Annapurna', 'Annapurna'), ('EverestRegion', 'Everest Region'), ('LangtangNationalPark', 'Langtang National Park'), ('Ghorepani', 'Ghorepani'), ('Ghandruk', 'Ghandruk'), ('GosaikundaLake', 'Gosaikunda Lake'), ('Machhapuchhre', 'Machhapuchhre'), ('Khaptad', 'Khaptad'), ('KoshiTappu', 'Koshi Tappu'), ('Rara', 'Rara'), ('Shey', 'Shey'), ('SheyLake', 'Shey Lake'), ('Bardia', 'Bardia'), ('Dharan', 'Dharan'), ('Illam', 'Illam'), ('Lalitpur', 'Lalitpur'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Location',
                'verbose_name_plural': 'Favorite Locations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'location')},
            },
        ),
    ]
