# Generated by Django 5.2.8 on 2026-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_favoritelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='location',
            field=models.CharField(choices=[('Illam', 'Illam'), ('Dharan', 'Dharan'), ('KoshiTappu', 'Koshi Tappu'), ('MtEverestBaseCamp', 'Mt Everest Base Camp'), ('MakaluTrekEverestRegion', 'Makalu Trek (Everest Region)'), ('MtEverestSummitAttempt', 'Mt Everest (Summit attempt)'), ('JanakiTemple', 'Janaki Temple'), ('GaurishankarRegionTrek', 'Gaurishankar Region Trek'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('LangtangValleyTrek', 'Langtang Valley (Trek)'), ('GosaikundaLake', 'Gosaikunda Lake'), ('MachapuchareFishtail', 'Machapuchare (Fishtail)'), ('GhandrukVillage', 'Ghandruk Village'), ('Pokhara', 'Pokhara'), ('PhewaLake', 'Phewa Lake'), ('GhorepaniPoonHill', 'Ghorepani–Poon Hill'), ('AnnapurnaCircuit', 'Annapurna Circuit'), ('AnnapurnaBaseCampABC', 'Annapurna Base Camp (ABC) Trek'), ('DhaulagiriCircuitTrek', 'Dhaulagiri Circuit Trek'), ('Lumbini', 'Lumbini'), ('BardiaNationalPark', 'Bardia National Park'), ('LangtangNationalPark', 'Langtang National Park'), ('SagarmathaNationalPark', 'Sagarmatha National Park'), ('RaraLake', 'Rara Lake'), ('RaraNationalPark', 'Rara National Park'), ('SheyPhoksundoLake', 'Shey Phoksundo Lake'), ('SheyPhoksundoNationalPark', 'Shey Phoksundo National Park'), ('ApiMountain', 'Api Mountain'), ('KhaptadNationalPark', 'Khaptad National Park'), ('Mustang', 'Mustang'), ('Manang', 'Manang')], default='Other', max_length=50),
        ),
    ]
