# Generated by Django 5.2.8 on 2026-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0002_alter_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelkit',
            name='price',
        ),
        migrations.AddField(
            model_name='travelkititem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
