# Generated by Django 5.2.8 on 2026-01-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0003_remove_travelkit_price_travelkititem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTravelKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='travelKit.travelkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_travel_kits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Travel Kit',
                'verbose_name_plural': 'Favorite Travel Kits',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'travel_kit')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteTravelKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='travelKit.travelkititem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Travel Kit Item',
                'verbose_name_plural': 'Favorite Travel Kit Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
