# Generated by Django 5.2.8 on 2026-02-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0004_userpersonalizedtravelkit_unique_user_location_travelkit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
