# Generated by Django 5.2.8 on 2026-02-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0005_alter_location_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpersonalizedtravelkit',
            name='unique_user_location_travelkit',
        ),
    ]
