# Generated by Django 5.2.8 on 2026-02-02 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0006_remove_userpersonalizedtravelkit_unique_user_location_travelkit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpersonalizedtravelkit',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='unique_user_location_travelkit'),
        ),
    ]
