# Generated by Django 5.2.8 on 2026-02-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelKit', '0004_favoritetravelkit_favoritetravelkititem'),
        ('travelKit', '0007_userpersonalizedtravelkit_unique_user_location_travelkit'),
    ]

    operations = [
    ]
