# Generated by Django 5.2.8 on 2026-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_user_activity_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_activity_notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
