# Generated by Django 5.2.8 on 2026-01-12 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sherpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField()),
                ('languages', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sherpa/photos/')),
                ('nid_document', models.FileField(blank=True, null=True, upload_to='sherpa/nid/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sherpa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
